title: PolakoView
email: i.bazarov096@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Stay on top of cryptocurrency news with PolakoView, your all-in-one crypto tracker. Whether you're a seasoned trader or just getting started in the world of digital assets, PolakoView offers the tools you need to monitor coins in one convenient app
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
